# Generated by Django 4.2.5 on 2023-10-29 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city', models.CharField(max_length=50, verbose_name='Where From?')),
                ('to_city', models.CharField(max_length=50, verbose_name='Where To?')),
                ('d_journey', models.DateField(default=datetime.date.today, verbose_name='Date of Journey')),
                ('n_persons', models.IntegerField(verbose_name='Number of Persons')),
            ],
        ),
    ]
