# Generated by Django 4.2.5 on 2023-10-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknow',
            name='d_journey',
            field=models.DateField(verbose_name='Date of Journey'),
        ),
    ]
